### ISSUE TITLE
How do I remove the output in debug mode?

### ISSUE THREAD

**Issue by Verteletsky** [yeqown/log#15]
Hi, 
When using 

`proxy.NewReverseProxy(addr, proxy.WithTimeout(5*time.Second))` 

the output in the 

`[DBG] "1669901401" dst="&{openBalance:false weights:[] addresses:[] tlsConfig:<nil> timeout:5000000000}" sourceOpts="[{f:0x77e440}]" msg="options applied"`

How do I remove the output of `[DBG] "1669901401"`?

The production also outputs `[DBG] "1669901401"`

**Comment by yeqown** [comment]
https://github.com/yeqown/fasthttp-reverse-proxy no longer depend on this package
