### ISSUE TITLE
return value mismatch 

### ISSUE THREAD

**Issue by abhijitgujar86** [yeqown/log#6]
while using it with fasthttp came with this error 
github.com/gophemt/fasthttp-reverse-proxy
../../../../go/src/github.com/gophemt/fasthttp-reverse-proxy/debug.go:9:2: assignment mismatch: 1 variable but "github.com/yeqown/log".NewLogger returns 2 values

**Comment by yeqown** [comment]
had fixed in `fasthttp-reverse-proxy`.
